# Generated by Django 4.0.5 on 2022-07-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='youtube_video_id',
            new_name='youtube_video_url',
        ),
    ]
