# Generated by Django 4.0.5 on 2022-07-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_youtube_video_id_project_youtube_video_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='ProjectDocument',
        ),
    ]
