# Generated by Django 4.0.5 on 2022-07-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_projectimages_projectimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='file',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
