# Generated by Django 4.0.5 on 2022-07-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_moderated',
        ),
    ]
