# Generated by Django 4.0.5 on 2022-07-18 04:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0010_remove_project_youtube_video_url_projectmedia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectvote',
            unique_together={('user', 'project')},
        ),
    ]
