# Generated by Django 4.0.5 on 2022-07-19 06:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_alter_projectvote_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Категория проекта', 'verbose_name_plural': 'Категории проектов'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='projectmedia',
            options={'verbose_name': 'Медиа', 'verbose_name_plural': 'Медиа'},
        ),
        migrations.AlterModelOptions(
            name='projectvote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='presentation',
            field=models.FileField(default=None, null=True, upload_to='project_presentations/', verbose_name='Презентация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(choices=[('created', 'Создан'), ('filled', 'На модерации'), ('moderated', 'Прошел модерацию')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Адрес ресурса'),
        ),
    ]
