# Generated by Django 4.0.5 on 2022-07-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='terms_files/')),
            ],
            options={
                'verbose_name': 'Файл страницы правил',
                'verbose_name_plural': 'Файл страницы правил',
            },
        ),
    ]
