# Generated by Django 4.0.5 on 2022-07-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_termspagefiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termspagefiles',
            options={'verbose_name': 'Файл страницы правил', 'verbose_name_plural': 'Файлы страницы правил'},
        ),
    ]
